name: NetteTester

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  tester:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2', '8.3' ]

    name: Tester ${{ matrix.php }}

    steps:
      - name: Composer update
        run: composer update --no-progress --no-interaction

      - name: Tester
        run: vendor/bin/tester .
